name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Display Python info
      - name: Python info
        run: |
          which python
          python --version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Show installed Python packages
      - name: Show pip list
        run: |
          pip list

      # Check code formatting with Black
      - name: Run Black (check formatting)
        run: black --diff --check --color .

      # Check import sorting with isort
      - name: Run isort (check import sorting)
        run: isort --check-only .

      # Run linter (ruff)
      - name: Run linter (ruff)
        run: |
          ruff check .

      # Run unit tests with pytest
      - name: Run unit tests with pytest
        run: pytest tests/
