name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Display Python version and location
      - name: Display Python version
        run: |
          echo "Python executable: $(which python)"
          python --version

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Step 5: Show installed Python packages
      - name: Show installed Python packages
        run: pip list

      # Step 6: Check and reformat code with Black
      - name: Run Black (format code)
        run: black .

      # Step 7: Automatically format imports with isort
      - name: Run isort (format imports)
        run: isort .

      # Step 8: Check import sorting with isort
      - name: Verify import sorting with isort
        run: isort --check-only .

      # Step 9: Run linter with Ruff
      - name: Run code linting with Ruff
        run: ruff check .

      # Step 10: Run tests with pytest
      - name: Execute tests with pytest
        run: pytest tests/

  generate-diagrams:
    name: Generate Profiling Diagrams
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install matplotlib pandas

      - name: Generate profiling diagrams
        run: python profiling/visualize_profiling.py

      - name: Upload profiling diagrams
        uses: actions/upload-artifact@v3
        with:
          name: profiling-diagrams
          path: profiling/profiling_visualization.png